routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/employees', 'EmployeeController');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $fillable  = ["firstname","lastname", "email", "contactno", "image", "username", "password"];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Hash;


class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all()->sortBy('last_name');
        return view('employees.index')->with('employees', $employees);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'firstname' => 'required|string',
            'lastname' => 'required|string',
            'contactno'=> 'required|numeric',
            'username' => 'required|string',
            'image' =>    'required|image|max:2000',
            'email' => 'required|unique:employees,email',
            'password' => 'required|string' 
        ]);


        $imageName = time().'.'.$request->image->getClientOriginalExtension();
        $request->image->move(public_path('/images/units'),$imageName);
        $employee = new Employee($validatedData);
        $employee->image = $imageName;
        $employee->password = Hash::make($request->password);
        $employee->save();
        return redirect(route('employees.index'))
            ->with('message', "Employee {$employee->lastname},{$employee->firstname} is added successfully") ;   
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('employees.edit')
            ->with('employee', $employee);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $validatedData = $request->validate([
            'firstname' => 'required|string',
            'lastname' => 'required|string',
            'contactno'=> 'required|numeric',
            'username' => 'required|string',
            'image' =>    'image|max:2000',
            'email' => 'required|unique:employees,email',
            'password' => 'required|string' 
        ]);
        $employee->update($validatedData);

         if($request->hasFile('image')){
           $imageName = time().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('/images/units'),$imageName);
            $employee->image = $imageName;
        }
        $employee->password = Hash::make($request->password);
        $employee->save();
        return redirect(route('employees.index'))
            ->with('message',"Employee is updated successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
       $employee->delete();
       return redirect(route('employees.index'))->with('message','Employee is deleted successfully')->with('alert',"danger");

    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/employees/create.blade.php
@extends ('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Create Employee
				</h1>
			</div>
		</div>
		{{-- start of form section --}}
		<div class="row">
			<div class="col-12 col-sm-6 mx-auto">
				<form 
					action="{{route('employees.store')}}" 
					method="post"
					enctype="multipart/form-data"
				>
					@csrf
					{{-- first_name --}}
					@include('employees.partials.form-group',[
						'name'=> 'firstname',
						'type'=> 'text',
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- last_name --}}
					@include('employees.partials.form-group',[
						'name'=> 'lastname',
						'type'=> 'text',
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- username --}}
					@include('employees.partials.form-group',[
						'name'=> 'username',
						'type'=> 'text',
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- email --}}
					@include('employees.partials.form-group',[
						'name'=> 'email',
						'type'=> 'email',
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- password --}}
					@include('employees.partials.form-group',[
						'name'=> 'password',
						'type'=> 'password',
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- contactno --}}
					@include('employees.partials.form-group',[
						'name'=> 'contactno',
						'type'=> 'text',
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- image --}}
					@include('employees.partials.form-group',[
						'name'=> 'image',
						'type'=> 'file',
						'classes'=> ['form-control-file', 'form-control-sm']
					])

					<button class="btn btn-sm btn-primary mt-3">
						Add Employee
					</button>


				</form>
			</div>
		</div>
		{{-- end of form section --}}
	</div>

@endsection

resources/views/employees/edit.blade.php
@extends ('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Edit Employee
				</h1>
			</div>
		</div>
		{{-- start of form section --}}
		<div class="row">
			<div class="col-12 col-sm-6 mx-auto">
				<form 
					action="{{route('employees.update', $employee->id)}}" 
					method="post"
					enctype="multipart/form-data"
				>
					@csrf
					@method('PUT')
					{{-- first_name --}}
					@include('employees.partials.form-group',[
						'name'=> 'firstname',
						'type'=> 'text',
						'value' => $employee->firstname,
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- last_name --}}
					@include('employees.partials.form-group',[
						'name'=> 'lastname',
						'type'=> 'text',
						'value' => $employee->lastname,
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- username --}}
					@include('employees.partials.form-group',[
						'name'=> 'username',
						'type'=> 'text',
						'value' => $employee->username,
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- email --}}
					@include('employees.partials.form-group',[
						'name'=> 'email',
						'type'=> 'email',
						'value' => $employee->email,
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- password --}}
					@include('employees.partials.form-group',[
						'name'=> 'password',
						'type'=> 'password',
						'value' => $employee->password,
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- contactno --}}
					@include('employees.partials.form-group',[
						'name'=> 'contactno',
						'type'=> 'text',
						'value' => $employee->contactno,
						'classes'=> ['form-control', 'form-control-sm']
					])
					{{-- image --}}
					@include('employees.partials.form-group',[
						'name'=> 'image',
						'type'=> 'file',
						'classes'=> ['form-control-file', 'form-control-sm']
					])

					<button class="btn btn-sm btn-primary mt-3 w-100">
						Edit Employee
					</button>


				</form>
			</div>
		</div>
		{{-- end of form section --}}
	</div>

@endsection

resources/views/employees/index.blade.php
@extends ('layouts.app')

@section('content')
	<div class="container container-fluid">
		{{-- header start --}}
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					List of Employees
				</h1>
			</div>
		</div>
		{{-- header end --}}
		{{-- alert message --}}
		@includeWhen(Session::has('message'),'partials.alert')
		<div class="row">
			@foreach($employees as $employee)
				<div class="col-12 col-sm-6 col-md-4 col-lg-3 mx-auto">
					{{-- employee card start --}}
					<div class="card">
						<img src="{{'http://localhost:8000/images/units/' . $employee->image }}" alt="" class="card-img-top">
						<div class="card-body">
							<h4 class="text-center">{{$employee->lastname}}, {{$employee->firstname}}</h4>
							<p>Email: {{$employee->email}}</p>
							<p>Password: {{$employee->password}}</p>
							<p>Username: {{$employee->username}}</p>
							<p>Contact Number: {{$employee->contactno}}</p>
						</div>
					</div>
					<div class="card-footer text-center">
						@include('employees.partials.edit')
						@include('employees.partials.delete')
					</div>
					{{-- employee card end --}}
				</div>
			@endforeach
		</div>
	</div>
@endsection

resources/views/employees/partials/delete.blade.php
<form action="{{route('employees.destroy', $employee->id)}}" method="post">
	@csrf
	@method('DELETE')
	<button class="btn btn-sm btn-danger w-100">Delete</button>
</form>

resources/views/employees/partials/edit.blade.php
<a href="{{route('employees.edit',$employee->id)}}" class="btn btn btn-sm btn-warning w-100 mb-1">Edit</a>

resources/views/employees/partials/form-group.blade.php
<div class="form-group">
	<label for="name"> Employee  {{$name}}</label>
	<input 
		type="{{$type}}" 
		name="{{$name}}"
		id="{{$name}}"
		class="
			@error($name) is-invalid @enderror
			@foreach($classes as $class)
				{{$class}}
			@endforeach
		"
		autofocus
		value="{{ isset($value) ? $value : ''}}"
	>
	@error($name)
	<small class="d-block invalid-feedback">
		<strong>{{$message}}</strong>
	</small>
	@enderror
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-link">
                            <a href="{{route('employees.index')}}">List of Employees</a>
                        </li>
                        <li class="nav-link">
                            <a href="{{route('employees.create')}}">Add Employee</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/partials/alert.blade.php
<div class="row">
	<div class="col-12">
		<div class="alert alert-{{Session::has('alert') ? Session::get('alert'):"info"}}">
			{{Session::get('message')}}
		</div>
	</div>
</div>